# Komodo Resource Definitions for dockervm-traefik
# This file defines all resources needed to deploy the Traefik stack via Komodo

[[stack]]
name = "dockervm-traefik"
description = "Traefik reverse proxy with socket proxy and SSL termination"
deploy = true
tags = ["infrastructure", "reverse-proxy", "traefik"]

[stack.config]
server_id = "dockervm"
file_paths = ["docker-compose.yml"]
run_directory = "."
env_file_path = ".env"
git_provider = "github.com"
repo = "basher83/dockervm-traefik"
branch = "main"
commit = ""  # Use latest commit
ignore_services = ["logrotate"]

# Environment variables for the stack
environment = """
TRAEFIK_VERSION=3.3
TZ=EST
DOMAIN=lab.spaceships.work
SSL_ENABLED=true
LETSENCRYPT_EMAIL=admin@lab.spaceships.work
TRAEFIK_HTTP_PORT=8081
TRAEFIK_HTTPS_PORT=8443
TRAEFIK_DASHBOARD_PORT=8082
SOCKET_PROXY_SUBNET=10.91.0.0/24
TRAEFIK_CPU_LIMIT=1
TRAEFIK_MEMORY_LIMIT=512M
METRICS_ENABLED=false
METRICS_PORT=8083
"""

# Pre-deploy command to ensure network exists
[stack.config.pre_deploy]
path = ""
command = "docker network create traefik-proxy --driver bridge --attachable || true"
