http:
  middlewares:
    # Security headers
    secure-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
          - POST
          - DELETE
        accessControlMaxAge: 100
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        referrerPolicy: "same-origin"
        customRequestHeaders:
          X-Forwarded-Proto: "https"
    
    # Default authentication (can be overridden per service)
    default-auth:
      basicAuth:
        users:
          - "admin:$2y$10$2b2cu2Fw2X2hCjPq8XzLve3hKDgWbgRAA4XqLs9U1LW.e8YKHpvXe"  # admin:admin123
    
    # Rate limiting
    rate-limit:
      rateLimit:
        burst: 100
        average: 50
