services:
  arcane:
    image: ghcr.io/ofkm/arcane:latest
    container_name: arcane
    ports:
      - '3000:3000'
    networks:
      - default
      - socket-proxy
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock # Use Docker Socket Proxy instead
      - arcane-data:/app/data
      # - /home/basher83/docker:/home/basher83/docker:ro
    environment:
      - APP_ENV=production # Required
      - PUBLIC_SESSION_SECRET=${PUBLIC_SESSION_SECRET}
      - DOCKER_HOST=tcp://socket-proxy:2375
      # Optional: Match your host user for permissions
      - PUID=1000
      - PGID=1000
      # Optional: Set if Docker access fails
      # - DOCKER_GID=998
      # Optional: For local HTTP testing only
      # - PUBLIC_ALLOW_INSECURE_COOKIES=true
    restart: unless-stopped

volumes:
  arcane-data:
    driver: local