services:
  orb-docker:
    image: orbforge/orb:latest
    container_name: orb-sensor # Optional: Give the container a specific name
    network_mode: host # Required: Allows Orb to see network traffic
    volumes:
      - orb-data:/root/.config/orb # Persists Orb configuration
    # Optional: Limit resources if needed
    # deploy:
    #   resources:
    #     limits:
    #       memory: 512m
    restart: always # Ensures Orb restarts if it stops or on system reboot
    labels:
      - 'com.centurylinklabs.watchtower.enable=true' # Enable auto-updates with Watchtower

  # Optional: Watchtower automatically updates the Orb image when a new version is released
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    networks:
      - socket-proxy
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock # Use Docker Socket Proxy instead
    environment:
      - DOCKER_HOST=tcp://socket-proxy:2375
    command: --label-enable --interval 3600 # Check for updates every hour (3600s)

volumes:
  orb-data: # Creates a named volume for persistent data

# Networks are defined in docker-compose-prod.yml